name: Flake8

on: [push]

jobs:
  flake8:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4.1.7
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.12
    - run: pip install flake8
    - run: flake8 solar_angles
