name: Static Code Analysis

on: [push]

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Pip Dependencies
      run: pip install -r requirements.txt

    - name: Run MyPy
      run: mypy solar_angles --disallow-untyped-calls --disallow-untyped-defs --check-untyped-defs
